language: java
jdk:
 - oraclejdk8
sudo: false
script: mvn clean test
deploy:
provider: heroku
  api_key:
    secure: sfslPV7jEG56D3VsCftZc7XTy32hjTXZECWqjJu42NcvP4AG/Rx18CkFTamxrvVwpeexkcGITvt7mx3uFYXksYep6kJBl4ley5JszkeP9pRqqvtVa+n/+C0xsclU1E71f5AnkBEU3n952GbwUGP9soww51OsyPLfQ2vZRUfGdRtXDTZUDwSQGQ2PPB07Sz8tZVoIYNFJ3Ww6lK74TzFCVmzx4I4ObjJCxvZhtLbtL+id7hfuh/p20wEQHeErKk/lrYoGdjkqzKWr/qSAZImq981NkEPZ8NA1sm0T4Z2DG1qPRb1C0VDL/w2DJMQqTneeG9sZWwLbsgI3JfluOjZ93UofkYBw6AxUe0F6SJIhcuQlfB/QD+OTrzqn/3WPRZVKecZzypkWW4dVoyvBps124KCiG+o0tgzJMtZ1cjS8+OBXrY4ihtUyoWods2QnTWzmSWjH1UW/BacUX+u+Wb27/cogQ/jy9XIkphkHGyBMRXsACpDXTUw/k0UcuKMtULROlwFA/9k5/FwRlJJARPIaxdHGxU+uEmFQirPBlbcsCMbAv1Qron87rpZ98QpqOuLWq3Yf0gtV/Sp00zQ7/4tTIPrXPi0Rl+/aI0KKZEFAOs5Cdwy8cXmppcq8zb9vmRhba/Ac46tO8eyg2xpk8bErvOAnai2Vr3+iAGsHI6kfyCA=

